/**
 * Every error code the API can return, grouped by domain.
 * @type {Readonly<Record<string, string>>}
 */
export const ErrorCodes = {
  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  MALFORMED_JSON: "MALFORMED_JSON",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  // Auth
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  INVALID_RESET_CODE: "INVALID_RESET_CODE",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  // Profile
  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
  ADDRESS_NOT_FOUND: "ADDRESS_NOT_FOUND",
  ADDRESS_LIMIT_REACHED: "ADDRESS_LIMIT_REACHED",
  ADDRESS_LABEL_TAKEN: "ADDRESS_LABEL_TAKEN",
  // Products
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  SKU_ALREADY_EXISTS: "SKU_ALREADY_EXISTS",
  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
  PREORDER_PRICE_REQUIRED: "PREORDER_PRICE_REQUIRED",
  PREORDERS_PENDING: "PREORDERS_PENDING",
  PREORDER_LIMIT_BELOW_RESERVED: "PREORDER_LIMIT_BELOW_RESERVED",
  STOCK_BELOW_RESERVED: "STOCK_BELOW_RESERVED",
  INSUFFICIENT_STOCK_FOR_PREORDERS: "INSUFFICIENT_STOCK_FOR_PREORDERS",
  PRODUCT_CHANGED: "PRODUCT_CHANGED",
  // Cart / orders
  CART_REQUIRES_UPDATE: "CART_REQUIRES_UPDATE",
  PREORDER_UNAVAILABLE: "PREORDER_UNAVAILABLE",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_NOT_CANCELLABLE: "ORDER_NOT_CANCELLABLE",
  ORDER_ADDRESS_LOCKED: "ORDER_ADDRESS_LOCKED",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  PREORDER_NOT_READY_TO_SHIP: "PREORDER_NOT_READY_TO_SHIP",
  // Admin
  CUSTOMER_NOT_FOUND: "CUSTOMER_NOT_FOUND",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  // Payments
  PAYMENT_NOT_ALLOWED: "PAYMENT_NOT_ALLOWED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  INVALID_WEBHOOK_SIGNATURE: "INVALID_WEBHOOK_SIGNATURE",
  // Uploads / images
  INVALID_UPLOAD: "INVALID_UPLOAD",
  PRODUCT_IMAGE_LIMIT_REACHED: "PRODUCT_IMAGE_LIMIT_REACHED",
  PRODUCT_IMAGE_NOT_FOUND: "PRODUCT_IMAGE_NOT_FOUND",
};

// Add an entry here whenever a new error code is added to ErrorCodes above,
// so every throw site for that code stays on the same status by default.
/**
 * Canonical HTTP status for each error code.
 * @type {Readonly<Record<string, number>>}
 */
export const ErrorStatusCodes = {
  [ErrorCodes.VALIDATION_ERROR]: 422,
  [ErrorCodes.MALFORMED_JSON]: 400,
  [ErrorCodes.UNAUTHORIZED]: 401,
  [ErrorCodes.FORBIDDEN]: 403,
  [ErrorCodes.ROUTE_NOT_FOUND]: 404,
  [ErrorCodes.INTERNAL_ERROR]: 500,
  [ErrorCodes.INVALID_CREDENTIALS]: 401,
  [ErrorCodes.ACCOUNT_DISABLED]: 403,
  [ErrorCodes.EMAIL_ALREADY_REGISTERED]: 409,
  [ErrorCodes.INVALID_RESET_CODE]: 400,
  [ErrorCodes.INVALID_RESET_TOKEN]: 400,
  [ErrorCodes.INVALID_CURRENT_PASSWORD]: 400,
  [ErrorCodes.ADDRESS_NOT_FOUND]: 404,
  [ErrorCodes.ADDRESS_LIMIT_REACHED]: 409,
  [ErrorCodes.ADDRESS_LABEL_TAKEN]: 409,
  [ErrorCodes.PRODUCT_NOT_FOUND]: 404,
  [ErrorCodes.SKU_ALREADY_EXISTS]: 409,
  [ErrorCodes.SLUG_ALREADY_EXISTS]: 409,
  [ErrorCodes.PREORDER_PRICE_REQUIRED]: 422,
  [ErrorCodes.PREORDERS_PENDING]: 409,
  [ErrorCodes.PREORDER_LIMIT_BELOW_RESERVED]: 409,
  [ErrorCodes.STOCK_BELOW_RESERVED]: 409,
  [ErrorCodes.INSUFFICIENT_STOCK_FOR_PREORDERS]: 409,
  [ErrorCodes.PRODUCT_CHANGED]: 409,
  [ErrorCodes.CART_REQUIRES_UPDATE]: 422,
  [ErrorCodes.PREORDER_UNAVAILABLE]: 409,
  [ErrorCodes.ORDER_NOT_FOUND]: 404,
  [ErrorCodes.ORDER_NOT_CANCELLABLE]: 409,
  [ErrorCodes.ORDER_ADDRESS_LOCKED]: 409,
  [ErrorCodes.INVALID_STATUS_TRANSITION]: 409,
  [ErrorCodes.PREORDER_NOT_READY_TO_SHIP]: 409,
  [ErrorCodes.CUSTOMER_NOT_FOUND]: 404,
  [ErrorCodes.TRANSACTION_NOT_FOUND]: 404,
  [ErrorCodes.PAYMENT_NOT_ALLOWED]: 409,
  [ErrorCodes.PAYMENT_NOT_FOUND]: 404,
  [ErrorCodes.INVALID_WEBHOOK_SIGNATURE]: 401,
  [ErrorCodes.INVALID_UPLOAD]: 400,
  [ErrorCodes.PRODUCT_IMAGE_LIMIT_REACHED]: 409,
  [ErrorCodes.PRODUCT_IMAGE_NOT_FOUND]: 404,
};
